### ISSUE TITLE
书中部分代码没有正确显示

### ISSUE THREAD

**Issue by qiantao94** [hltj/kotlin-reference-chinese#1]
感谢作者您的翻译及分享，但是书中的好多代码都没有被解析出来，还是markdown格式的，希望作者您可以审查修改下

**Comment by hltj** [comment]
1.1 起有些格式部分还需要处理。
因为采用引用 https://github.com/hltj/kotlin-web-site-cn 的方式，实现方案我还在看。会尽快解决的。
