### ISSUE TITLE
一些翻译建议

### ISSUE THREAD

**Issue by attsion** [hltj/kotlin-reference-chinese#2]
1. 建议将文档的`委托`和`委托属性`分别翻译为`代理`和`代理属性`，因为该内容是对代理模式的实现，而且c#中委托有其他含义，容易造成混淆。
2. 建议将文档的`对象` 翻译为`对象表达式和对象声明`，否则容易误解为`类-对象`中的对象。
感谢作者的辛勤劳动。

**Comment by hltj** [comment]
我觉得这两条并没有问题。
1. `委托`对应的英文是`delegate`或`delegation`，`代理`对应的是`proxy`，你在维基百科中既能看到“代理模式”也能看到“委托模式”，中英文都是这样。翻译成什么由原文是什么来确定更能忠于原文。实际上这个词并非 C# 发明了，而是 Kotlin 和 C# 都用了同一词表达相应的含义。
2. 也是参考原文：https://kotlinlang.org/docs/reference/object-declarations.html 原文的导航栏里用的是 `Objects`所以翻译为`对象`，原文的文章标题为`Object Expressions and Declarations`所以翻译为`对象表达式与对象声明`。

欢迎继续提意见和建议，也欢迎参与到翻译中来。

**Comment by attsion** [comment]
谢谢作者回应，我仍然有一些看法，当然仅仅限于讨论：
1. 官方文档原文确实是`delegation pattern`,应该翻译为代理模式，但是我查询了GOF关于设计模式的内容是`proxy pattern`，我google了相关的区别，有些人确实说了一些区别，比如：[Delegation_vs._Proxy_pattern](https://en.wikipedia.org/wiki/Talk:Delegation_pattern#Delegation_vs._Proxy_pattern)，但是我认为大体可以认为两个模式是相同的，在国内一般是翻译为`代理模式`多一些，能便于大多数人的理解。
2. 原文标题是`Objects`，是复数形式，我认为这是英文`Object Expressions and Declarations`的省略写法。
