### ISSUE TITLE
String中没有找到toIntOrNull()方法

### ISSUE THREAD

**Issue by ttxz** [hltj/kotlin-reference-chinese#3]
作者，您好，最近在学习Kotlin语法时，学到了基础语法的"使用可空值及 null 检测"这一项，但是在使用AndroidStudio照例练习代码时，发现String中toIntOrNull()方法未找到，不知道是何原因，还请解答？

**Comment by hltj** [comment]
`toIntOrNull` 并非方法，而是扩展函数。另外是从 1.1 才引入的，请更新到最新版的 Kotlin。
参见其官方文档：
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-int-or-null.html

**Comment by ttxz** [comment]
好的，多谢了
