### ISSUE TITLE
pdf文件前三个索引没有链接地址

### ISSUE THREAD

**Issue by f839903061** [hltj/kotlin-reference-chinese#4]
学习 Kotlin
文档
Kotlin 文档是一个很好的起点，可查看以下链接来学习：
**_

1. 基础
2. 习惯用法
3. 与 Java 互操作

_**

pdf文件中的，上面的三个没有链接!

**Comment by hltj** [comment]
感谢反馈，新构建的 pdf 应该已修正。
有问题欢迎随时反馈~
