### ISSUE TITLE
所有gitbook的pdf链接都无法查看，下载

### ISSUE THREAD

**Issue by chasefish** [hltj/kotlin-reference-chinese#5]
如点击 字大版 PDF 会跳转到gitbook的首页

**Comment by hltj** [comment]
了解，GitBook 强制改版了，以前的好多功能不能用了，在尝试自己构建

**Comment by stydxm** [comment]
> 
> 
> 了解，GitBook 强制改版了，以前的好多功能不能用了，在尝试自己构建

尝试成功了吗，kindle看pdf不太方便，希望有mobi或者epub的

**Comment by zcr268** [comment]
目前还是不能下载呢.是不再继续了么?

**Comment by hltj** [comment]
> 目前还是不能下载呢.是不再继续了么?

在看了，不过工作太忙了，一直没能抽出足够多时间

**Comment by hltj** [comment]
@chasefish @stydxm @zcr268 

解决了，新的在线阅读地址：https://book.kotlincn.net/

epub： [kotlincn-docs.epub](https://book.kotlincn.net/kotlincn-docs.epub)
mobi：[kotlincn-docs.mobi](https://book.kotlincn.net/kotlincn-docs.mobi)
字大版 pdf：[kotlincn-docs.pdf](https://book.kotlincn.net/kotlincn-docs.pdf)
